name: Docker build beavermake

on:
  schedule:
    - cron:  '0 6 * * 5'  # 每周五，早上 6 点（UTC 时间）
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]
    paths:
      - 'beavermake/**'
      - '.github/workflows/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read  # 仅保留需要的权限
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./beavermake
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/beavermake:latest
          # 可以考虑添加更多的标签，例如 ${{ github.sha }} 或版本号