name: Docker build beavermake

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ master ]
 
env:
  REGISTRY: docker.io
  IMAGE_NAME: beavermake

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./beavermake
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/beavermake:latest
    
      
      
